# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

Vagrant.configure("2") do |config|
  # always use Vagrants insecure key
#  config.ssh.insert_key = false

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.4.195"

  config.vm.define "cab-01" do |t|
  end
  config.vm.hostname = "cab-01"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision :ansible do |ansible|
   ansible.playbook = "proxy.yml"
   ansible.inventory_path = "hosts"
   ansible.verbose = "v"
   ansible.limit = "all"
  end
end
